<?xml version="1.0" encoding="utf-8"?><testsuites><testsuite name="pytest" errors="0" failures="1" skipped="0" tests="17" time="0.945" timestamp="2021-05-18T11:44:47.081424" hostname="DESKTOP-2UOT798"><testcase classname="test.test_accum" name="test_accumulator_init" time="0.001" /><testcase classname="test.test_accum" name="test_accumulator_add_one" time="0.001" /><testcase classname="test.test_accum" name="test_accumulator_add_three" time="0.000" /><testcase classname="test.test_accum" name="test_accumulator_add_twice" time="0.000" /><testcase classname="test.test_accum" name="test_accumulator_cannot_set_count_directly" time="0.001" /><testcase classname="test.test_math" name="test_one_plus_one" time="0.001"><failure message="assert (1 + 1) == 200">def test_one_plus_one():
&gt;       assert 1 + 1 == 200
E       assert (1 + 1) == 200

test\test_math.py:12: AssertionError</failure></testcase><testcase classname="test.test_math" name="test_one_plus_two" time="0.001" /><testcase classname="test.test_math" name="test_divide_by_zero" time="0.000" /><testcase classname="test.test_math" name="test_multiplication[2-3-6]" time="0.001" /><testcase classname="test.test_math" name="test_multiplication[1-99-99]" time="0.001" /><testcase classname="test.test_math" name="test_multiplication[0-99-0]" time="0.000" /><testcase classname="test.test_math" name="test_multiplication[2--3--6]" time="0.001" /><testcase classname="test.test_math" name="test_multiplication[-3--3-9]" time="0.001" /><testcase classname="test.test_math" name="test_multiplication[2.5-6.7-16.75]" time="0.001" /><testcase classname="test.test_math" name="test_multiply_two_positive_integers" time="0.000" /><testcase classname="test.test_math" name="test_multiply_identity" time="0.000" /><testcase classname="test.test_math" name="test_multiply_zero" time="0.000" /></testsuite></testsuites>